/* 
 * HTTP API
 *
 * The Service HTTP API
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using BadAPIIqvia.Client;
using BadAPIIqvia.Model;

namespace BadAPIIqvia.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITweetsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get our super-awesome curated tweets
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BadAPIIqvia.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="startDate">Earliest entry timestamp in UTC (inclusive, ie. &#39;2018-03-20T04:07:56.271Z&#39;)</param>
        /// <param name="endDate">Latest entry timestamp in UTC (inclusive, ie. &#39;2018-03-20T04:07:56.271Z&#39;)</param>
        /// <returns>List&lt;Tweet&gt;</returns>
        List<Tweet> ApiV1TweetsGet (DateTime? startDate, DateTime? endDate);

        /// <summary>
        /// Get our super-awesome curated tweets
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BadAPIIqvia.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="startDate">Earliest entry timestamp in UTC (inclusive, ie. &#39;2018-03-20T04:07:56.271Z&#39;)</param>
        /// <param name="endDate">Latest entry timestamp in UTC (inclusive, ie. &#39;2018-03-20T04:07:56.271Z&#39;)</param>
        /// <returns>ApiResponse of List&lt;Tweet&gt;</returns>
        ApiResponse<List<Tweet>> ApiV1TweetsGetWithHttpInfo (DateTime? startDate, DateTime? endDate);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Get our super-awesome curated tweets
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BadAPIIqvia.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="startDate">Earliest entry timestamp in UTC (inclusive, ie. &#39;2018-03-20T04:07:56.271Z&#39;)</param>
        /// <param name="endDate">Latest entry timestamp in UTC (inclusive, ie. &#39;2018-03-20T04:07:56.271Z&#39;)</param>
        /// <returns>Task of List&lt;Tweet&gt;</returns>
        System.Threading.Tasks.Task<List<Tweet>> ApiV1TweetsGetAsync (DateTime? startDate, DateTime? endDate);

        /// <summary>
        /// Get our super-awesome curated tweets
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BadAPIIqvia.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="startDate">Earliest entry timestamp in UTC (inclusive, ie. &#39;2018-03-20T04:07:56.271Z&#39;)</param>
        /// <param name="endDate">Latest entry timestamp in UTC (inclusive, ie. &#39;2018-03-20T04:07:56.271Z&#39;)</param>
        /// <returns>Task of ApiResponse (List&lt;Tweet&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<Tweet>>> ApiV1TweetsGetAsyncWithHttpInfo (DateTime? startDate, DateTime? endDate);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class TweetsApi : ITweetsApi
    {
        private BadAPIIqvia.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="TweetsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TweetsApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = BadAPIIqvia.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TweetsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public TweetsApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = BadAPIIqvia.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public BadAPIIqvia.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Get our super-awesome curated tweets 
        /// </summary>
        /// <exception cref="BadAPIIqvia.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="startDate">Earliest entry timestamp in UTC (inclusive, ie. &#39;2018-03-20T04:07:56.271Z&#39;)</param>
        /// <param name="endDate">Latest entry timestamp in UTC (inclusive, ie. &#39;2018-03-20T04:07:56.271Z&#39;)</param>
        /// <returns>List&lt;Tweet&gt;</returns>
        public List<Tweet> ApiV1TweetsGet (DateTime? startDate, DateTime? endDate)
        {
             ApiResponse<List<Tweet>> localVarResponse = ApiV1TweetsGetWithHttpInfo(startDate, endDate);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get our super-awesome curated tweets 
        /// </summary>
        /// <exception cref="BadAPIIqvia.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="startDate">Earliest entry timestamp in UTC (inclusive, ie. &#39;2018-03-20T04:07:56.271Z&#39;)</param>
        /// <param name="endDate">Latest entry timestamp in UTC (inclusive, ie. &#39;2018-03-20T04:07:56.271Z&#39;)</param>
        /// <returns>ApiResponse of List&lt;Tweet&gt;</returns>
        public ApiResponse< List<Tweet> > ApiV1TweetsGetWithHttpInfo (DateTime? startDate, DateTime? endDate)
        {
            // verify the required parameter 'startDate' is set
            if (startDate == null)
                throw new ApiException(400, "Missing required parameter 'startDate' when calling TweetsApi->ApiV1TweetsGet");
            // verify the required parameter 'endDate' is set
            if (endDate == null)
                throw new ApiException(400, "Missing required parameter 'endDate' when calling TweetsApi->ApiV1TweetsGet");

            var localVarPath = "/api/v1/Tweets";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (startDate != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "startDate", startDate)); // query parameter
            if (endDate != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "endDate", endDate)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiV1TweetsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<Tweet>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<Tweet>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<Tweet>)));
        }

        /// <summary>
        /// Get our super-awesome curated tweets 
        /// </summary>
        /// <exception cref="BadAPIIqvia.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="startDate">Earliest entry timestamp in UTC (inclusive, ie. &#39;2018-03-20T04:07:56.271Z&#39;)</param>
        /// <param name="endDate">Latest entry timestamp in UTC (inclusive, ie. &#39;2018-03-20T04:07:56.271Z&#39;)</param>
        /// <returns>Task of List&lt;Tweet&gt;</returns>
        public async System.Threading.Tasks.Task<List<Tweet>> ApiV1TweetsGetAsync (DateTime? startDate, DateTime? endDate)
        {
             ApiResponse<List<Tweet>> localVarResponse = await ApiV1TweetsGetAsyncWithHttpInfo(startDate, endDate);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get our super-awesome curated tweets 
        /// </summary>
        /// <exception cref="BadAPIIqvia.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="startDate">Earliest entry timestamp in UTC (inclusive, ie. &#39;2018-03-20T04:07:56.271Z&#39;)</param>
        /// <param name="endDate">Latest entry timestamp in UTC (inclusive, ie. &#39;2018-03-20T04:07:56.271Z&#39;)</param>
        /// <returns>Task of ApiResponse (List&lt;Tweet&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<Tweet>>> ApiV1TweetsGetAsyncWithHttpInfo (DateTime? startDate, DateTime? endDate)
        {
            // verify the required parameter 'startDate' is set
            if (startDate == null)
                throw new ApiException(400, "Missing required parameter 'startDate' when calling TweetsApi->ApiV1TweetsGet");
            // verify the required parameter 'endDate' is set
            if (endDate == null)
                throw new ApiException(400, "Missing required parameter 'endDate' when calling TweetsApi->ApiV1TweetsGet");

            var localVarPath = "/api/v1/Tweets";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (startDate != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "startDate", startDate)); // query parameter
            if (endDate != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "endDate", endDate)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiV1TweetsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<Tweet>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<Tweet>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<Tweet>)));
        }

    }
}
