/* 
 * HTTP API
 *
 * The Service HTTP API
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = BadAPIIqvia.Client.SwaggerDateConverter;

namespace BadAPIIqvia.Model
{
    /// <summary>
    /// A tweet from Twitter
    /// </summary>
    [DataContract]
    public partial class Tweet :  IEquatable<Tweet>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Tweet" /> class.
        /// </summary>
        /// <param name="Id">The unique identifier of the tweet.</param>
        /// <param name="Stamp">The timestamp, in UTC, of the tweet.</param>
        /// <param name="Text">The content of the tweet.</param>
        public Tweet(string Id = default(string), DateTime? Stamp = default(DateTime?), string Text = default(string))
        {
            this.Id = Id;
            this.Stamp = Stamp;
            this.Text = Text;
        }
        
        /// <summary>
        /// The unique identifier of the tweet
        /// </summary>
        /// <value>The unique identifier of the tweet</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// The timestamp, in UTC, of the tweet
        /// </summary>
        /// <value>The timestamp, in UTC, of the tweet</value>
        [DataMember(Name="stamp", EmitDefaultValue=false)]
        public DateTime? Stamp { get; set; }

        /// <summary>
        /// The content of the tweet
        /// </summary>
        /// <value>The content of the tweet</value>
        [DataMember(Name="text", EmitDefaultValue=false)]
        public string Text { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Tweet {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Stamp: ").Append(Stamp).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Tweet);
        }

        /// <summary>
        /// Returns true if Tweet instances are equal
        /// </summary>
        /// <param name="input">Instance of Tweet to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Tweet input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Stamp == input.Stamp ||
                    (this.Stamp != null &&
                    this.Stamp.Equals(input.Stamp))
                ) && 
                (
                    this.Text == input.Text ||
                    (this.Text != null &&
                    this.Text.Equals(input.Text))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Stamp != null)
                    hashCode = hashCode * 59 + this.Stamp.GetHashCode();
                if (this.Text != null)
                    hashCode = hashCode * 59 + this.Text.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
